# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/af6618/C_TANK

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/af6618/C_TANK

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/af6618/C_TANK/CMakeFiles /home/af6618/C_TANK//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/af6618/C_TANK/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TANK

# Build rule for target.
TANK: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TANK
.PHONY : TANK

# fast build rule for target.
TANK/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/build
.PHONY : TANK/fast

#=============================================================================
# Target rules for targets named P2PTest

# Build rule for target.
P2PTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 P2PTest
.PHONY : P2PTest

# fast build rule for target.
P2PTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/build
.PHONY : P2PTest/fast

buffers/VirtualRDMARingBuffer.o: buffers/VirtualRDMARingBuffer.c.o
.PHONY : buffers/VirtualRDMARingBuffer.o

# target to build an object file
buffers/VirtualRDMARingBuffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/buffers/VirtualRDMARingBuffer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/buffers/VirtualRDMARingBuffer.c.o
.PHONY : buffers/VirtualRDMARingBuffer.c.o

buffers/VirtualRDMARingBuffer.i: buffers/VirtualRDMARingBuffer.c.i
.PHONY : buffers/VirtualRDMARingBuffer.i

# target to preprocess a source file
buffers/VirtualRDMARingBuffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/buffers/VirtualRDMARingBuffer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/buffers/VirtualRDMARingBuffer.c.i
.PHONY : buffers/VirtualRDMARingBuffer.c.i

buffers/VirtualRDMARingBuffer.s: buffers/VirtualRDMARingBuffer.c.s
.PHONY : buffers/VirtualRDMARingBuffer.s

# target to generate assembly for a file
buffers/VirtualRDMARingBuffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/buffers/VirtualRDMARingBuffer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/buffers/VirtualRDMARingBuffer.c.s
.PHONY : buffers/VirtualRDMARingBuffer.c.s

buffers/VirtualSHMDoubleRingBuffer.o: buffers/VirtualSHMDoubleRingBuffer.c.o
.PHONY : buffers/VirtualSHMDoubleRingBuffer.o

# target to build an object file
buffers/VirtualSHMDoubleRingBuffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/buffers/VirtualSHMDoubleRingBuffer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/buffers/VirtualSHMDoubleRingBuffer.c.o
.PHONY : buffers/VirtualSHMDoubleRingBuffer.c.o

buffers/VirtualSHMDoubleRingBuffer.i: buffers/VirtualSHMDoubleRingBuffer.c.i
.PHONY : buffers/VirtualSHMDoubleRingBuffer.i

# target to preprocess a source file
buffers/VirtualSHMDoubleRingBuffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/buffers/VirtualSHMDoubleRingBuffer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/buffers/VirtualSHMDoubleRingBuffer.c.i
.PHONY : buffers/VirtualSHMDoubleRingBuffer.c.i

buffers/VirtualSHMDoubleRingBuffer.s: buffers/VirtualSHMDoubleRingBuffer.c.s
.PHONY : buffers/VirtualSHMDoubleRingBuffer.s

# target to generate assembly for a file
buffers/VirtualSHMDoubleRingBuffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/buffers/VirtualSHMDoubleRingBuffer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/buffers/VirtualSHMDoubleRingBuffer.c.s
.PHONY : buffers/VirtualSHMDoubleRingBuffer.c.s

buffers/VirtualSHMRingBuffer.o: buffers/VirtualSHMRingBuffer.c.o
.PHONY : buffers/VirtualSHMRingBuffer.o

# target to build an object file
buffers/VirtualSHMRingBuffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/buffers/VirtualSHMRingBuffer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/buffers/VirtualSHMRingBuffer.c.o
.PHONY : buffers/VirtualSHMRingBuffer.c.o

buffers/VirtualSHMRingBuffer.i: buffers/VirtualSHMRingBuffer.c.i
.PHONY : buffers/VirtualSHMRingBuffer.i

# target to preprocess a source file
buffers/VirtualSHMRingBuffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/buffers/VirtualSHMRingBuffer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/buffers/VirtualSHMRingBuffer.c.i
.PHONY : buffers/VirtualSHMRingBuffer.c.i

buffers/VirtualSHMRingBuffer.s: buffers/VirtualSHMRingBuffer.c.s
.PHONY : buffers/VirtualSHMRingBuffer.s

# target to generate assembly for a file
buffers/VirtualSHMRingBuffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/buffers/VirtualSHMRingBuffer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/buffers/VirtualSHMRingBuffer.c.s
.PHONY : buffers/VirtualSHMRingBuffer.c.s

client/RdmaClient.o: client/RdmaClient.c.o
.PHONY : client/RdmaClient.o

# target to build an object file
client/RdmaClient.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/client/RdmaClient.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/client/RdmaClient.c.o
.PHONY : client/RdmaClient.c.o

client/RdmaClient.i: client/RdmaClient.c.i
.PHONY : client/RdmaClient.i

# target to preprocess a source file
client/RdmaClient.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/client/RdmaClient.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/client/RdmaClient.c.i
.PHONY : client/RdmaClient.c.i

client/RdmaClient.s: client/RdmaClient.c.s
.PHONY : client/RdmaClient.s

# target to generate assembly for a file
client/RdmaClient.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/client/RdmaClient.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/client/RdmaClient.c.s
.PHONY : client/RdmaClient.c.s

client/SharedMemoryClient.o: client/SharedMemoryClient.c.o
.PHONY : client/SharedMemoryClient.o

# target to build an object file
client/SharedMemoryClient.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/client/SharedMemoryClient.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/client/SharedMemoryClient.c.o
.PHONY : client/SharedMemoryClient.c.o

client/SharedMemoryClient.i: client/SharedMemoryClient.c.i
.PHONY : client/SharedMemoryClient.i

# target to preprocess a source file
client/SharedMemoryClient.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/client/SharedMemoryClient.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/client/SharedMemoryClient.c.i
.PHONY : client/SharedMemoryClient.c.i

client/SharedMemoryClient.s: client/SharedMemoryClient.c.s
.PHONY : client/SharedMemoryClient.s

# target to generate assembly for a file
client/SharedMemoryClient.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/client/SharedMemoryClient.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/client/SharedMemoryClient.c.s
.PHONY : client/SharedMemoryClient.c.s

client/TcpClient.o: client/TcpClient.c.o
.PHONY : client/TcpClient.o

# target to build an object file
client/TcpClient.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/client/TcpClient.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/client/TcpClient.c.o
.PHONY : client/TcpClient.c.o

client/TcpClient.i: client/TcpClient.c.i
.PHONY : client/TcpClient.i

# target to preprocess a source file
client/TcpClient.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/client/TcpClient.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/client/TcpClient.c.i
.PHONY : client/TcpClient.c.i

client/TcpClient.s: client/TcpClient.c.s
.PHONY : client/TcpClient.s

# target to generate assembly for a file
client/TcpClient.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/client/TcpClient.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/client/TcpClient.c.s
.PHONY : client/TcpClient.c.s

connections/P2PConnection.o: connections/P2PConnection.c.o
.PHONY : connections/P2PConnection.o

# target to build an object file
connections/P2PConnection.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/connections/P2PConnection.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/connections/P2PConnection.c.o
.PHONY : connections/P2PConnection.c.o

connections/P2PConnection.i: connections/P2PConnection.c.i
.PHONY : connections/P2PConnection.i

# target to preprocess a source file
connections/P2PConnection.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/connections/P2PConnection.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/connections/P2PConnection.c.i
.PHONY : connections/P2PConnection.c.i

connections/P2PConnection.s: connections/P2PConnection.c.s
.PHONY : connections/P2PConnection.s

# target to generate assembly for a file
connections/P2PConnection.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/connections/P2PConnection.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/connections/P2PConnection.c.s
.PHONY : connections/P2PConnection.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/main.c.s
.PHONY : main.c.s

rdma/CompletionQueuePair.o: rdma/CompletionQueuePair.c.o
.PHONY : rdma/CompletionQueuePair.o

# target to build an object file
rdma/CompletionQueuePair.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/CompletionQueuePair.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/CompletionQueuePair.c.o
.PHONY : rdma/CompletionQueuePair.c.o

rdma/CompletionQueuePair.i: rdma/CompletionQueuePair.c.i
.PHONY : rdma/CompletionQueuePair.i

# target to preprocess a source file
rdma/CompletionQueuePair.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/CompletionQueuePair.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/CompletionQueuePair.c.i
.PHONY : rdma/CompletionQueuePair.c.i

rdma/CompletionQueuePair.s: rdma/CompletionQueuePair.c.s
.PHONY : rdma/CompletionQueuePair.s

# target to generate assembly for a file
rdma/CompletionQueuePair.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/CompletionQueuePair.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/CompletionQueuePair.c.s
.PHONY : rdma/CompletionQueuePair.c.s

rdma/Network.o: rdma/Network.c.o
.PHONY : rdma/Network.o

# target to build an object file
rdma/Network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/Network.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/Network.c.o
.PHONY : rdma/Network.c.o

rdma/Network.i: rdma/Network.c.i
.PHONY : rdma/Network.i

# target to preprocess a source file
rdma/Network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/Network.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/Network.c.i
.PHONY : rdma/Network.c.i

rdma/Network.s: rdma/Network.c.s
.PHONY : rdma/Network.s

# target to generate assembly for a file
rdma/Network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/Network.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/Network.c.s
.PHONY : rdma/Network.c.s

rdma/QueuePair.o: rdma/QueuePair.c.o
.PHONY : rdma/QueuePair.o

# target to build an object file
rdma/QueuePair.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/QueuePair.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/QueuePair.c.o
.PHONY : rdma/QueuePair.c.o

rdma/QueuePair.i: rdma/QueuePair.c.i
.PHONY : rdma/QueuePair.i

# target to preprocess a source file
rdma/QueuePair.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/QueuePair.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/QueuePair.c.i
.PHONY : rdma/QueuePair.c.i

rdma/QueuePair.s: rdma/QueuePair.c.s
.PHONY : rdma/QueuePair.s

# target to generate assembly for a file
rdma/QueuePair.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/QueuePair.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/QueuePair.c.s
.PHONY : rdma/QueuePair.c.s

rdma/RDMANetworking.o: rdma/RDMANetworking.c.o
.PHONY : rdma/RDMANetworking.o

# target to build an object file
rdma/RDMANetworking.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/RDMANetworking.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/RDMANetworking.c.o
.PHONY : rdma/RDMANetworking.c.o

rdma/RDMANetworking.i: rdma/RDMANetworking.c.i
.PHONY : rdma/RDMANetworking.i

# target to preprocess a source file
rdma/RDMANetworking.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/RDMANetworking.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/RDMANetworking.c.i
.PHONY : rdma/RDMANetworking.c.i

rdma/RDMANetworking.s: rdma/RDMANetworking.c.s
.PHONY : rdma/RDMANetworking.s

# target to generate assembly for a file
rdma/RDMANetworking.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/RDMANetworking.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/RDMANetworking.c.s
.PHONY : rdma/RDMANetworking.c.s

rdma/RcQueuePair.o: rdma/RcQueuePair.c.o
.PHONY : rdma/RcQueuePair.o

# target to build an object file
rdma/RcQueuePair.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/RcQueuePair.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/RcQueuePair.c.o
.PHONY : rdma/RcQueuePair.c.o

rdma/RcQueuePair.i: rdma/RcQueuePair.c.i
.PHONY : rdma/RcQueuePair.i

# target to preprocess a source file
rdma/RcQueuePair.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/RcQueuePair.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/RcQueuePair.c.i
.PHONY : rdma/RcQueuePair.c.i

rdma/RcQueuePair.s: rdma/RcQueuePair.c.s
.PHONY : rdma/RcQueuePair.s

# target to generate assembly for a file
rdma/RcQueuePair.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/RcQueuePair.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/RcQueuePair.c.s
.PHONY : rdma/RcQueuePair.c.s

rdma/UcQueuePair.o: rdma/UcQueuePair.c.o
.PHONY : rdma/UcQueuePair.o

# target to build an object file
rdma/UcQueuePair.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/UcQueuePair.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/UcQueuePair.c.o
.PHONY : rdma/UcQueuePair.c.o

rdma/UcQueuePair.i: rdma/UcQueuePair.c.i
.PHONY : rdma/UcQueuePair.i

# target to preprocess a source file
rdma/UcQueuePair.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/UcQueuePair.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/UcQueuePair.c.i
.PHONY : rdma/UcQueuePair.c.i

rdma/UcQueuePair.s: rdma/UcQueuePair.c.s
.PHONY : rdma/UcQueuePair.s

# target to generate assembly for a file
rdma/UcQueuePair.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/UcQueuePair.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/UcQueuePair.c.s
.PHONY : rdma/UcQueuePair.c.s

rdma/UdQueuePair.o: rdma/UdQueuePair.c.o
.PHONY : rdma/UdQueuePair.o

# target to build an object file
rdma/UdQueuePair.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/UdQueuePair.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/UdQueuePair.c.o
.PHONY : rdma/UdQueuePair.c.o

rdma/UdQueuePair.i: rdma/UdQueuePair.c.i
.PHONY : rdma/UdQueuePair.i

# target to preprocess a source file
rdma/UdQueuePair.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/UdQueuePair.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/UdQueuePair.c.i
.PHONY : rdma/UdQueuePair.c.i

rdma/UdQueuePair.s: rdma/UdQueuePair.c.s
.PHONY : rdma/UdQueuePair.s

# target to generate assembly for a file
rdma/UdQueuePair.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/rdma/UdQueuePair.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/rdma/UdQueuePair.c.s
.PHONY : rdma/UdQueuePair.c.s

server/RdmaServer.o: server/RdmaServer.c.o
.PHONY : server/RdmaServer.o

# target to build an object file
server/RdmaServer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/server/RdmaServer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/server/RdmaServer.c.o
.PHONY : server/RdmaServer.c.o

server/RdmaServer.i: server/RdmaServer.c.i
.PHONY : server/RdmaServer.i

# target to preprocess a source file
server/RdmaServer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/server/RdmaServer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/server/RdmaServer.c.i
.PHONY : server/RdmaServer.c.i

server/RdmaServer.s: server/RdmaServer.c.s
.PHONY : server/RdmaServer.s

# target to generate assembly for a file
server/RdmaServer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/server/RdmaServer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/server/RdmaServer.c.s
.PHONY : server/RdmaServer.c.s

server/SharedMemoryServer.o: server/SharedMemoryServer.c.o
.PHONY : server/SharedMemoryServer.o

# target to build an object file
server/SharedMemoryServer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/server/SharedMemoryServer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/server/SharedMemoryServer.c.o
.PHONY : server/SharedMemoryServer.c.o

server/SharedMemoryServer.i: server/SharedMemoryServer.c.i
.PHONY : server/SharedMemoryServer.i

# target to preprocess a source file
server/SharedMemoryServer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/server/SharedMemoryServer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/server/SharedMemoryServer.c.i
.PHONY : server/SharedMemoryServer.c.i

server/SharedMemoryServer.s: server/SharedMemoryServer.c.s
.PHONY : server/SharedMemoryServer.s

# target to generate assembly for a file
server/SharedMemoryServer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/server/SharedMemoryServer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/server/SharedMemoryServer.c.s
.PHONY : server/SharedMemoryServer.c.s

server/TcpServer.o: server/TcpServer.c.o
.PHONY : server/TcpServer.o

# target to build an object file
server/TcpServer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/server/TcpServer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/server/TcpServer.c.o
.PHONY : server/TcpServer.c.o

server/TcpServer.i: server/TcpServer.c.i
.PHONY : server/TcpServer.i

# target to preprocess a source file
server/TcpServer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/server/TcpServer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/server/TcpServer.c.i
.PHONY : server/TcpServer.c.i

server/TcpServer.s: server/TcpServer.c.s
.PHONY : server/TcpServer.s

# target to generate assembly for a file
server/TcpServer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/server/TcpServer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/server/TcpServer.c.s
.PHONY : server/TcpServer.c.s

test/P2PTest.o: test/P2PTest.c.o
.PHONY : test/P2PTest.o

# target to build an object file
test/P2PTest.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/test/P2PTest.c.o
.PHONY : test/P2PTest.c.o

test/P2PTest.i: test/P2PTest.c.i
.PHONY : test/P2PTest.i

# target to preprocess a source file
test/P2PTest.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/test/P2PTest.c.i
.PHONY : test/P2PTest.c.i

test/P2PTest.s: test/P2PTest.c.s
.PHONY : test/P2PTest.s

# target to generate assembly for a file
test/P2PTest.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/test/P2PTest.c.s
.PHONY : test/P2PTest.c.s

test/bench.o: test/bench.c.o
.PHONY : test/bench.o

# target to build an object file
test/bench.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/test/bench.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/test/bench.c.o
.PHONY : test/bench.c.o

test/bench.i: test/bench.c.i
.PHONY : test/bench.i

# target to preprocess a source file
test/bench.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/test/bench.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/test/bench.c.i
.PHONY : test/bench.c.i

test/bench.s: test/bench.c.s
.PHONY : test/bench.s

# target to generate assembly for a file
test/bench.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/test/bench.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/test/bench.c.s
.PHONY : test/bench.c.s

utils/utils.o: utils/utils.c.o
.PHONY : utils/utils.o

# target to build an object file
utils/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/utils/utils.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/utils/utils.c.o
.PHONY : utils/utils.c.o

utils/utils.i: utils/utils.c.i
.PHONY : utils/utils.i

# target to preprocess a source file
utils/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/utils/utils.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/utils/utils.c.i
.PHONY : utils/utils.c.i

utils/utils.s: utils/utils.c.s
.PHONY : utils/utils.s

# target to generate assembly for a file
utils/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/utils/utils.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/utils/utils.c.s
.PHONY : utils/utils.c.s

utils/vec.o: utils/vec.c.o
.PHONY : utils/vec.o

# target to build an object file
utils/vec.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/utils/vec.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/utils/vec.c.o
.PHONY : utils/vec.c.o

utils/vec.i: utils/vec.c.i
.PHONY : utils/vec.i

# target to preprocess a source file
utils/vec.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/utils/vec.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/utils/vec.c.i
.PHONY : utils/vec.c.i

utils/vec.s: utils/vec.c.s
.PHONY : utils/vec.s

# target to generate assembly for a file
utils/vec.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/utils/vec.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/utils/vec.c.s
.PHONY : utils/vec.c.s

utils/virtualMemory.o: utils/virtualMemory.c.o
.PHONY : utils/virtualMemory.o

# target to build an object file
utils/virtualMemory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/utils/virtualMemory.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/utils/virtualMemory.c.o
.PHONY : utils/virtualMemory.c.o

utils/virtualMemory.i: utils/virtualMemory.c.i
.PHONY : utils/virtualMemory.i

# target to preprocess a source file
utils/virtualMemory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/utils/virtualMemory.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/utils/virtualMemory.c.i
.PHONY : utils/virtualMemory.c.i

utils/virtualMemory.s: utils/virtualMemory.c.s
.PHONY : utils/virtualMemory.s

# target to generate assembly for a file
utils/virtualMemory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TANK.dir/build.make CMakeFiles/TANK.dir/utils/virtualMemory.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P2PTest.dir/build.make CMakeFiles/P2PTest.dir/utils/virtualMemory.c.s
.PHONY : utils/virtualMemory.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... P2PTest"
	@echo "... TANK"
	@echo "... buffers/VirtualRDMARingBuffer.o"
	@echo "... buffers/VirtualRDMARingBuffer.i"
	@echo "... buffers/VirtualRDMARingBuffer.s"
	@echo "... buffers/VirtualSHMDoubleRingBuffer.o"
	@echo "... buffers/VirtualSHMDoubleRingBuffer.i"
	@echo "... buffers/VirtualSHMDoubleRingBuffer.s"
	@echo "... buffers/VirtualSHMRingBuffer.o"
	@echo "... buffers/VirtualSHMRingBuffer.i"
	@echo "... buffers/VirtualSHMRingBuffer.s"
	@echo "... client/RdmaClient.o"
	@echo "... client/RdmaClient.i"
	@echo "... client/RdmaClient.s"
	@echo "... client/SharedMemoryClient.o"
	@echo "... client/SharedMemoryClient.i"
	@echo "... client/SharedMemoryClient.s"
	@echo "... client/TcpClient.o"
	@echo "... client/TcpClient.i"
	@echo "... client/TcpClient.s"
	@echo "... connections/P2PConnection.o"
	@echo "... connections/P2PConnection.i"
	@echo "... connections/P2PConnection.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... rdma/CompletionQueuePair.o"
	@echo "... rdma/CompletionQueuePair.i"
	@echo "... rdma/CompletionQueuePair.s"
	@echo "... rdma/Network.o"
	@echo "... rdma/Network.i"
	@echo "... rdma/Network.s"
	@echo "... rdma/QueuePair.o"
	@echo "... rdma/QueuePair.i"
	@echo "... rdma/QueuePair.s"
	@echo "... rdma/RDMANetworking.o"
	@echo "... rdma/RDMANetworking.i"
	@echo "... rdma/RDMANetworking.s"
	@echo "... rdma/RcQueuePair.o"
	@echo "... rdma/RcQueuePair.i"
	@echo "... rdma/RcQueuePair.s"
	@echo "... rdma/UcQueuePair.o"
	@echo "... rdma/UcQueuePair.i"
	@echo "... rdma/UcQueuePair.s"
	@echo "... rdma/UdQueuePair.o"
	@echo "... rdma/UdQueuePair.i"
	@echo "... rdma/UdQueuePair.s"
	@echo "... server/RdmaServer.o"
	@echo "... server/RdmaServer.i"
	@echo "... server/RdmaServer.s"
	@echo "... server/SharedMemoryServer.o"
	@echo "... server/SharedMemoryServer.i"
	@echo "... server/SharedMemoryServer.s"
	@echo "... server/TcpServer.o"
	@echo "... server/TcpServer.i"
	@echo "... server/TcpServer.s"
	@echo "... test/P2PTest.o"
	@echo "... test/P2PTest.i"
	@echo "... test/P2PTest.s"
	@echo "... test/bench.o"
	@echo "... test/bench.i"
	@echo "... test/bench.s"
	@echo "... utils/utils.o"
	@echo "... utils/utils.i"
	@echo "... utils/utils.s"
	@echo "... utils/vec.o"
	@echo "... utils/vec.i"
	@echo "... utils/vec.s"
	@echo "... utils/virtualMemory.o"
	@echo "... utils/virtualMemory.i"
	@echo "... utils/virtualMemory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

